{% set name = "micromagneticdata" %}
{% set version = "0.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcf28b3db2b7b597cec37e53fbcbcce4aea082b8d94ca3b1174cf79f8639a41d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield >=0.61.0,<0.62.0
    - ubermagtable >=0.61.0,<0.62.0
test:
  imports:
    - micromagneticdata
  commands:
    - python -c "import sys; import micromagneticdata; sys.exit(micromagneticdata.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python tools for the analysis of computational magnetism data.
  doc_url: https://ubermag.github.io/documentation/micromagneticdata.html
  dev_url: https://github.com/ubermag/micromagneticdata

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
