{% set name = "micromagneticdata" %}
{% set version = "0.3.1" %}
{% set sha256 = "fe62d5f9bc1e5fafbbced292ff746efc2680cc0437eb5df66ccd3156bb64a976" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - discretisedfield ==0.8.12
    - ubermagtable ==0.1.11

test:
  imports:
    - micromagneticdata
  commands:
    - python -c "import sys; import micromagneticdata as md; sys.exit(md.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis of micromagnetic data.
  doc_url: http://micromagneticdata.readthedocs.io
  dev_url: https://github.com/ubermag/micromagneticdata

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
