{% set name = "micromagneticdata" %}
{% set version = "0.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8817c8e177d262f33c3846d2261c1f017afb729581d2cbb44ba41e8faef647bb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield ==0.11.1
    - ubermagtable ==0.6.1
test:
  imports:
    - micromagneticdata
  commands:
    - python -c "import sys; import micromagneticdata; sys.exit(micromagneticdata.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python tools for the analysis of computational magnetism data.
  doc_url: http://micromagneticdata.readthedocs.io
  dev_url: https://github.com/ubermag/micromagneticdata

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
