{% set name = "micromagneticdata" %}
{% set version = "0.65.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14e7b514711e631e31e898d1558ce50a898778bb6aa733efa5c642814cedf442

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield >=0.65.0
    - ubermagtable >=0.61.1
test:
  imports:
    - micromagneticdata
  commands:
    - python -c "import sys; import micromagneticdata; sys.exit(micromagneticdata.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python tools for the analysis of computational magnetism data.
  doc_url: https://ubermag.github.io/documentation/micromagneticdata.html
  dev_url: https://github.com/ubermag/micromagneticdata

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
