travis:
  secure:
    BINSTAR_TOKEN: H66mQ10oN/QR0egIGk9usi1zGlcjFEWv6PZMa+zCIcA2QwrZcqZjxhPGQqJD5bdjbDwAcjfgkKg5SGpLcFwJNNZ5oN//b5ODbQXKopbfbCfvXhNwjaWnC0avMLnPQEsGasQbfJAvS9P+yaZawB1LD5h6VN1qFbFFvHt0QyW+iPp/FbX4HFhAehS6qq6GJUtNSsprKTt32Rx+vT8s5S3BwReiLIcAPG+HsGWbAzsOxoH9PxCUB6faQVd297BMlDGwb85c9vejy88Jlx+6gapQ2UDG/WTr/vcZsdZ3dj5AAqSgCakoQEEsbWSbtr8uOAr+pdEA5PNnkzKDH8qPCFA3jFxna3LDCiiPiMw9Rg4v74N7ULW8R3wJrPzyVyV26nXfDtA84fciV5c6sQFIGEEm5KEj3ADCNY/+tKinkn1699C60vIZqI1OpTnX+lAPOKZXvdTFs/uL7MsHXkJiD6EQFtOFM4G/tHB8G6Figi4liyRuGYdo48MQGS1cuDRuBmGZhhS8MLJaygIKfihSdR9enBvKui6dHW81s3OPUR3pBmfG/5uWpU0EVicOQdvLB+V7mf6cvo02Mm+nNu7dSFrulx+60GGcZDMxQR2rXX66uGtJDAcI0VUN4Mc4TgowWng2bH6siheBgsQch9pS9IPi6AirtRhKQAhaaIj3OCx8zFw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
